name: Render CV

on:
  workflow_dispatch:
  push:
    paths:
      - Curriculum_Vitae.typ

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v4

      - name: Compile to SVG
        run: typst compile --font-path fonts/ Curriculum_Vitae.typ "preview-{p}.svg"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: render preview SVGs"
          file_pattern: "preview-*.svg"
